# Базовый образ
FROM python:3.12-slim

# Установить рабочую директорию в контейнере
WORKDIR /app

# Скопировать файл зависимостей
COPY requirements.txt .

# Установить зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Скопировать весь код из папки web-quest-backend в контейнер
COPY . .

# Запуск приложения
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
